### ISSUE TITLE
Error code in F8 console and Custom sets not working

### ISSUE THREAD

**Issue by ConductorWon** [TrevorBarns/luxart-vehicle-control#10]
Hello,

2 issues, not sure if they are related or not:

1st: There is an error in the console when the script is started 
![image](https://user-images.githubusercontent.com/76677480/103193057-f7cf1900-488f-11eb-9298-d71d09aa8494.png)

2nd: I have set up custom siren settings in the VEHICLES file but they are not being followed. My fire trucks are still using the default setting.

**Comment by TrevorBarns** [comment]
#1 Ahh I see the issue, I can solve issue one tomorrow morning. Issue #2 is more difficult. 

#2 Verify that in profile name is shown on the right side of the storage management menu.
For example "Save -> (DEFAULT)" if it looks like this, the display name of the vehicle is not aligned with what is in the VEHICLES.lua. As outlined on line 36 of the default VEHICLES.lua:
> Where 'paleto1' is the vehicele's **<modelName>** as defined in vehicles.meta. Spaces will not work, underscores may work though. 
_I think this is also case sensitive._ 

If all of the above seems to be correct, then, I may have just found another issue. I just did a quick search regarding `GetDisplayNameFromVehicleModel`, which is used to locate the profile and apparently it does not like name longer than 8 characters. This will need additional testing but, if this is the case I will solve it and publish an update tomorrow solving both of these issues. 

Thank you for the report! 🥇 💯

**Comment by ConductorWon** [comment]
The model name is the same as the one that is in my vehicles.meta, is the same case, and is only 3 characters long with no space (FD1)

**Comment by TrevorBarns** [comment]
So in game under the storage management menu on the right does it read FD1 or DEFAULT?

**Comment by ConductorWon** [comment]
Default

**Comment by TrevorBarns** [comment]
I'm sorry, for some reason I mixed up the string pulled when writing the VEHICLES.lua. The name needs to match the `<gameName>` and not the model name. Please check this. I am also writing an update right now that will display this to the user if a profile is not found.

**Comment by ConductorWon** [comment]
Interesting, okay. Thanks for the response!

**Comment by ConductorWon** [comment]
Is there any way to make it reference the Model name instead?

**Comment by TrevorBarns** [comment]
Unfortunately this is not easily possible. There is no GTA V native to retrieve `<modelName>` even though that is the most convenient. Of course, there is always a work around. For example, in VEHICLES.lua we could create a vehicles table with `<gameName>` as the table index(?).
VEHICLES.lua:
```
vehicles = {
["DEFAULT"] = {1,2,3},
["FIRETRUK"] = {1,2,4},
["2006 Chevy Impala"] = {1,2,3},
["Los Santos Fire Engine"] = {1,2,3},
[<gameName>] = {tones}
}
```

Which would allow servers to retain custom game names but, makes VEHICLE.lua a little harder to read. It would be more efficient too. I might change to this.

**Comment by ConductorWon** [comment]
Does the game name have to be one of the generic ones that GTA uses and not a custom one?

**Comment by TrevorBarns** [comment]
In the idea above, no, the game name would match what is written in vehicles.meta

**Comment by ConductorWon** [comment]
But currently, it needs to be?

**Comment by TrevorBarns** [comment]
No for example if I have a vehicle with game name "so1"
and I have a profile in VEHICLES.lua: so1= {1,2,3}

It will work.

**Comment by ConductorWon** [comment]
Okay, that's what I thought. would it work if I have multiple vehicles with the same game name?

**Comment by TrevorBarns** [comment]
Well, it would work but, both vehicles would pull the same profile you would have to differentiate them in order for them to work differently in LVC.

**Comment by ConductorWon** [comment]
But say I have Firetruck = { 12, 13, 14, 11 } and set all my fire truck names to Firetruck that should work right?

**Comment by TrevorBarns** [comment]
Correct.
