### ISSUE TITLE
i need to turn on the warning lights

### ISSUE THREAD

**Issue by DeCuteEboi** [TrevorBarns/luxart-vehicle-control#11]
i need to turn on the warning lights but i want it to be de primary can i change that and how?

**Comment by TrevorBarns** [comment]
I'm sorry I don't follow. Warning lights? Like ELS? or hazard lights? Primary what?

**Comment by DeCuteEboi** [comment]
Yes i have ELS working but de hazard lights need to be on to turn on the siren i was wondering if there is something in the script i can change to set it to primary

**Comment by TrevorBarns** [comment]
Okay,
ELS - flashing lights to warn drivers of approaching emergency vehicles. 
Hazard Lights - (aka 4-ways) are amber lights that blink and are equipped on all motor vehicles. 

The hazard lights do not have to be on to activate the siren. ELS does have to be on, too activate the siren. Your descriptions are not in depth enough to explain your request. 

Set what to primary? Are you trying to have the hazards turn on automatically with ELS?
