### ISSUE TITLE
Resource needs restart every 30 minutes or so - Sirens don't work for specific people after a while

### ISSUE THREAD

**Issue by MazaTv** [TrevorBarns/luxart-vehicle-control#12]
With about 25 people on beta server with no conflicting scripts, after a bit (Approx. 15-20 mins) All sounds controlled by the Lux vehicle control just stops for specific people and doesn't work/play audio. 
Had to revert to stable version with no menu.

**Comment by TrevorBarns** [comment]
I'm well aware of this issue. I have not found a way to resolve it.

How many people did you have with the script? I have had average failure period of around 1-2 hours. If it that fast if you could record a video of the failure it would greatly help other developers understand the issue.

**Comment by MazaTv** [comment]
Hi,
We had a beta period with this script for about an hour or two, and the average failure time was ranging from 10-25 minutes.
We had about 20 players on at the time.
I can go ahead and test rn and send you results. Thanks!

**Comment by MazaTv** [comment]
It just broke for 3 of us. About 34 40 minutes

**Comment by TrevorBarns** [comment]
What version are you using? You can find this fxmanifest.

**Comment by MazaTv** [comment]
Latest Beta version, 3.1.5
Another issue is we are using a custom commonmenu.ytd with this latest version, we followed instructions and added textures to commonmenu.ytd, and the Rmenu seemed to break/limit it and break the UI.

**Comment by TrevorBarns** [comment]
You'll have to be more descriptive. Did it break the LVC HUD? How did it effect the UI?

The commonmenu.ytd simply provides textures for the LVC HUD, rage menu handles all other UI interactions.

**Comment by MazaTv** [comment]
Yes, it broke the UI, leaving white and grey boxes in place of the Lux UI siren box. 
I tested a version earlier where Rage Menu was not present and it no longer had grey boxes and was fixed.
I suspect it is the Rage Menu but that's my testing portion of it.

**Comment by TrevorBarns** [comment]
A server or client restart should have solved that. It can happen when FiveM unloads the streamed texture while players are still in the server. I have not received any reports of texture issues after server restart for months of use.

Note: the later versions pull a different texture name meaning commonmenu.ytd would have have to be updated and restreamed by the server.

**Comment by MazaTv** [comment]
We tried many times to re stream it and restarted the server. Apologies but i have tried solutions many times

**Comment by TrevorBarns** [comment]
Did you clear the cached files that you used for the older version? My only guess I'll test with an new server later.

**Comment by MazaTv** [comment]
Neg, i will try when im free later. Thanks!

**Comment by MazaTv** [comment]
Also one thing i noticed was when our sounds cut off - it was like instant for multiple people at the same time. And it was when someone else was testing sirens who just joined.

**Comment by TrevorBarns** [comment]
Solved as of v3.1.6, I was stupidly calling to PlaySoundFromEntity with a 0 value.
