### ISSUE TITLE
HUD Settings Crash

### ISSUE THREAD

**Issue by phillf** [TrevorBarns/luxart-vehicle-control#22]
**Describe the bug**
When selecting HUD Settings from the lux_vehcontrols menu said menu crashes and then cannot be reopened with F9 unless player disconnects and reconnects to the server.

**To Reproduce**
1. Open lux_vehcontrols with F9 (or configured bind)
2. Select HUD Settings

**Expected behavior**
Display the HUD settings menu.

**Screenshots**
Console: ![image](https://user-images.githubusercontent.com/1618828/112477550-834e2e00-8d49-11eb-8933-f446a05369d7.png)

**Extra Context**
These are the plugins that are enabled at the time of this report:

# These resources will start by default.
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure fivem
ensure hardcap
ensure rconlog
ensure scoreboard
ensure cron
ensure fivem-map-hipster
ensure txAdmin
ensure RageUI

# Vehicles
ensure 2020FPIUUM
ensure stealth16fpiu
ensure 2020IMPALA

#vrp
ensure ghmattimysql
ensure vrp_mysql
ensure vrp
ensure vrp_playernames
ensure vrp_basic_mission
ensure vrp_barbershop
ensure vrp_carwash
ensure vrp_loadfreeze
ensure vRP_AdvancedFuel
ensure vrp_job_display
ensure vrp_bankrobbery
ensure vrp_basic_menu
ensure vrp_barrier
ensure vrp_TruckerJob
ensure vrp_ubermission
ensure vrp_fixdvcar
ensure vrp_hotkeys
ensure vrp_doors
ensure railhouse
ensure online
ensure bob74_ipl
ensure pvp
ensure Ped

#condensed scripts (non-vrp)
ensure CustomScripts

#police skins
ensure PolicePeds

#vMenu
ensure vMenu
ensure kgv-phone

# Handling
ensure handling

# Vechile Extentisons
ensure lux_vehcontrol

**Comment by TrevorBarns** [comment]
Please try updating to latest release, verify you are using RageUI provided in dependencies, it had additional modifications to improve menu operations.

**Comment by TrevorBarns** [comment]
This issue was caused by using an older RageUI download, LVC has made improvements to the now discontinued RageUI.
