### ISSUE TITLE
HUD showing up on random vehicles

### ISSUE THREAD

**Issue by LukeM03** [TrevorBarns/luxart-vehicle-control#24]
On random vehicles in Utility, Commerical, Industrial and others the HUD will appear when spawning from Emergency to sed vehicle classes. This also crashes game from time to time.

**Comment by LukeM03** [comment]
This happens when you spawn in a vehicle after an emergency. The HUD doesn't go away. Diff Bug

**Comment by TrevorBarns** [comment]
I am not able to reproduce this on 3.2.3, please try updating and reporting back.
