### ISSUE TITLE
Random number on screen when using sirens.

### ISSUE THREAD

**Issue by IdrisDose** [TrevorBarns/luxart-vehicle-control#25]
Hello, when I toggle my sirens on a random number appears on the screen (5000) and goes down in a loop increments of 500. Screenshot attached shows it at 2000. Stops counting down when it hits 0 and then loops back up to 5000.

![image](https://user-images.githubusercontent.com/2646100/117412615-51d79d80-af58-11eb-8d47-585fc20d7104.png)

Version: 3.2.2

**Comment by TrevorBarns** [comment]
Delete smart siren plugin, it has not been released, number is used for development purposes.

**Comment by IdrisDose** [comment]
Thanks heaps, my bad. :)
