### ISSUE TITLE
Counting number on hud removal help

### ISSUE THREAD

**Issue by zhivotnoya** [TrevorBarns/luxart-vehicle-control#26]
![image](https://user-images.githubusercontent.com/3652539/119261592-14a11b80-bba6-11eb-99e7-ba134e1c70a6.png)

This counter counts backwards when playing the siren audio.  Is there a way to remove it?

**Comment by arkhunter623** [comment]
Downloading the master branch is what causes this. Please try downloading a RELEASE instead. You can find them listed on the right of the screen under releases.

**Comment by zhivotnoya** [comment]
Thank you.
