### ISSUE TITLE
Suggestion:  Integrating DLS lighting configs for stage lighting

### ISSUE THREAD

**Issue by zhivotnoya** [TrevorBarns/luxart-vehicle-control#27]
It's a very good design upgrade you have here.  Adding DLS lighting config support would take it to the next level.  DLS (Dynamic Lighting System) is something that was made for non-ELS cars on single player to give you Multi-stage lights.  Especially helpful when you can't find your favorite cars (my case vanilla enhanced) in ELS.

Just a thought.  (Not an issue)

Maybe it something you've got on your radar, but thought I'd offer it up.

**Comment by TrevorBarns** [comment]
Unfortunately, this is not possible in FiveM. DLS edits the games memory which is not allowed in FiveM. CitizenFX may at some point allow for a native to do this.

Alternatively we are working on extra based light stages. By placing light meshes / sirens (not light bar/modules) under extras we can effectively turn on and off light stages. This comes at the cost of vehicle customization depending on how many stages / features are implemented.

Thank you for contributing to LVC. 😃

**Comment by zhivotnoya** [comment]
Thanks for the info!  Well I like what you've done so far to provide an alternative to ELS for us lore vehicle lovers.  Keep up the great work!
