### ISSUE TITLE
TA Bar Example Config

### ISSUE THREAD

**Issue by dawenzlik** [TrevorBarns/luxart-vehicle-control#28]
Hey,
i just installed it but i can't get it to work. I currently use this Pack 

https://gtapolicemods.com/files/file/739-non-els-working-ta-barlore-friendly-chp-vehicle-pack-working-spotlight-reflective-liveries/

and tried the following:

`--------------------TRAFFIC ADVISOR SETTINGS---------------------
ta_masterswitch = true
--	Determines if traffic_advisor plugin can be activated.
ta_combokey = false
--  Key that needs to be pressed in combination with registered key mapping. Set to false to disable. (default: disabled (false))

--[[ Documentation / Wiki: https://github.com/TrevorBarns/luxart-vehicle-control/wiki/Traffic-Advisor ]]

TA_ASSIGNMENTS = {
  ['DEFAULT'] = {   lightbar = 3 
      left = { on = { add = 11, remove = 10, repair = true }, off = { add = { 10 }, remove = { 11 } } }, 
      right = { on = { add = 12, remove = 10, repair = true }, off = { add = { 10 }, remove = { 12 } } }, 
      middle = { on = { add = { 10 }, remove = {}, repair = true }, off = { add = {}, remove = { 10 } } }, 
    },   

`
The Left Function is on Extra11, the right function on Extra12, Middle on Extra10.

Can anyone help me out?

Is it correct that i trigger the TA with the indicator-buttons? Or do they have extra keys? Would be great if the Wiki Pages could be more detailed :)

Thank you :)

**Comment by 4iY** [comment]
Uh, you're assigning all of that to the `'DEFAULT'` profile - replace that with the vehicle's actual spawncode and it should work. I don't see anything inherently wrong here. Oh, and you need to copy and paste that assignments for every single vehicle, from what I know there's no way to do that for several at once.

**Comment by TrevorBarns** [comment]
@dawenzlik has this issue been resolved?

**Comment by dawenzlik** [comment]
Thanks for the help, i got it working :)
