### ISSUE TITLE
Work with ELS?

### ISSUE THREAD

**Issue by Senlar** [TrevorBarns/luxart-vehicle-control#29]
I have some rmod police cars and they do not work with this. Any way to accommodate ELS here?

**Comment by ConductorWon** [comment]
This is specifically a non-els script. There are scripts out there that are made to work with ELS vehicle

**Comment by arkhunter623** [comment]
Unfortunately no. LVC only supports non-els.

**Comment by TrevorBarns** [comment]
Unfortunately not. ELS is a far more complex system than default GTA V siren lighting. ELS is laggy and requires more server overhead. Someone may use my ideas from LVC to improve upon their ELS script but, LVC will likely never support ELS vehicles.
