### ISSUE TITLE
LVC enabling/disabling random extras on vehicles

### ISSUE THREAD

**Issue by PC1up** [TrevorBarns/luxart-vehicle-control#31]
So pretty simple, on some emergency vehicles LVC is just removing the lightbar. Is there some way to fix this?
I think it does not delete the lightbar on vehicles where the lightbar is an extra you can enable and disable but does delete it on vehicle where the lightbar is not an extra.

Edit: Appearently its just adding and removing random extras
2nd Edit: It does also delete extras on saved vehicles where, for example, Extra 1 is enabled and Extra 2 is disabled, LVC ist just disabling Extra 1 or something like that

~Paul

**Comment by TrevorBarns** [comment]
LVC is not capable of toggling a light bar if it is NOT an extra. If it is an extra, there are couple of plugins possible that could be toggling it. Try temporarily removing all the plugins from the plugin folder, can delete or move to desktop for example.

**Comment by PC1up** [comment]
Okay so
1. LVC does actually light up the lightbar on vehicles where it is not an extra and
2. A plugin really removed the lightbar, got it fixed
thank you :)

~Paul
