### ISSUE TITLE
Some players can't enable lights

### ISSUE THREAD

**Issue by PC1up** [TrevorBarns/luxart-vehicle-control#32]
Hey,
I searched for this issue and found something: #12
So TrevorBarns said, this is fixed, but I still get this issue. LVC works fine at first but also after about 30 minutes it breaks for some users and needs a restart. I got the newest version of LVC.

~Paul

**Comment by TrevorBarns** [comment]
Different issue than #12, that is solved but could have similar symptoms. Need error messages from the clients that it stopped working on. This could be found in FiveM/Logs.

**Comment by PC1up** [comment]
Asked them, there were no error messages. Just nothing happened when they tried to enable the lights with **Q**

**Comment by TrevorBarns** [comment]
Please provide their log files I highly doubt no console (F8) messages were fired. I need something to off of.

**Comment by PC1up** [comment]
Alright, I'll ask them

**Comment by PC1up** [comment]
So appearently no one has this issue atm. I'll let you know if I find someone and then send you the logs

**Comment by PC1up** [comment]
I found an user. I just asked him for the log in FiveM Application Data/logs and then for the latest log, here you go:
[CitizenFX_log_2021-08-09T114632.log](https://github.com/TrevorBarns/luxart-vehicle-control/files/6954449/CitizenFX_log_2021-08-09T114632.log)

**Comment by TrevorBarns** [comment]
It's a known but will be fixed soon with latest update release coming.

**Comment by TrevorBarns** [comment]
Solved in Release 3.2.4.
