### ISSUE TITLE
Cannot read property "left" of undefined

### ISSUE THREAD

**Issue by Lutton-alliance** [TrevorBarns/luxart-vehicle-control#33]
Uncaught typeError: Cannot read property "left" of undefined 

Error apparently occurs in UI/html/lvc.js line 96

There also is another issue that nobody else can hear your sirens (using wm-serversirens) after a while (unknown if connected to this issue, but probably not)

**Comment by TrevorBarns** [comment]
Yes, this is an error LVC has received for a while now. It does not have an effect on functionality or stability. Think of it more as a warning. Has to do with saving hud position after reset.

In regards to sirens shutting off using wm-ss I'll have to look into that.. How long after? Does it happen with regular sirens?

**Comment by Lutton-alliance** [comment]
The sirens appeared to have turned off when in a group of 5-6 were on; only some though. We could only hear default gta 5 police cars (not even addon cars which had the default siren attached)

**Comment by TrevorBarns** [comment]
> The sirens appeared to have turned off when in a group of 5-6 were on; only some though. We could only hear default gta 5 police cars (not even addon cars which had the default siren attached)

Likely an error occurred crashing the client side for some people. Review their FiveM logs under `FiveM AppData/logs` see if you find any errors with "lvc" in it. 

Which version is this?

**Comment by TrevorBarns** [comment]
Could be an LVC bug or a configuration error (WM-ServerSirens Integration) that is resulting in some unintended results.

**Comment by Lutton-alliance** [comment]
Yeah could be, I will let you know if it happens again I guess

**Comment by Lutton-alliance** [comment]
[CitizenFX_log_2021-08-12T214145.log](https://github.com/TrevorBarns/luxart-vehicle-control/files/6978825/CitizenFX_log_2021-08-12T214145.log)

**Comment by TrevorBarns** [comment]
So I do not see any errors in the log or in your SIRENS.lua. So LVC will continue working for default sirens from resident.rpf, but WM-ServerSiren tones break? Disregard any sounds coming from AI cops because LVC does not control them so even if LVC breaks, AI cops will continue to work. 

- How often and how quickly does it occur? 
- Can you get a video of it happening?
- What happens when officers try and toggle siren after it has happened?
- Continue to try and find any errors in logs from clients or server when it occurs.

**Comment by Lutton-alliance** [comment]
So whenever it "breaks", there are no siren sounds emitted from a server sided perspective. Only the client can hear their own siren and nobody else. As of now, it does not work at all, irregardless of server restarts or anything. Players may toggle it on and off but only they will hear the siren.

**Comment by TrevorBarns** [comment]
Are you on OneSync?

**Comment by Lutton-alliance** [comment]
We are not using OneSync no.

**Comment by TrevorBarns** [comment]
This is embarrassing, a mistake was made in prep for 3.2.4 release which resulted in incorrect event names. Please download the new revision 1 release here: https://github.com/TrevorBarns/luxart-vehicle-control/releases/tag/3.2.4

Sorry for any inconvenience.

**Comment by Lutton-alliance** [comment]
All good no worries; Im sure I have made worse mistakes
