### ISSUE TITLE
Issues with HUD ( v3.2.5 beta ) [Linux Globbing]

### ISSUE THREAD

**Issue by Dlackjack** [TrevorBarns/luxart-vehicle-control#34]
Images of buttons and switches are not loaded in the beta version (3.2.5 beta)
![Image of the problem](https://user-images.githubusercontent.com/48407834/129318471-d7af289a-2fda-405b-8ddc-a1caba34b082.png)

**Comment by TrevorBarns** [comment]
What operating system is the server on?

**Comment by Dlackjack** [comment]
> What operating system is the server on?

Linux

**Comment by TrevorBarns** [comment]
⚠️ This resource utilizes globbing which may not be supported in some linux environments. 

I have went ahead and removed globbing you can read more here: [docs.fivem.net - Globbing](https://docs.fivem.net/docs/scripting-reference/resource-manifest/resource-manifest/#globbing)

I have went ahead and created fxmanifest for linux users and have attached it.

[LVC 3.2.5-beta fxmanifest - Linux.zip](https://github.com/TrevorBarns/luxart-vehicle-control/files/6986694/LVC.3.2.5-beta.fxmanifest.-.Linux.zip)

**Comment by Dlackjack** [comment]
I changed the fxmanifest, but the problem was not solved, what should I do?

**Comment by TrevorBarns** [comment]
Did you `refresh` and ensure? The fxmanifest is loaded on server restart or refresh.

**Comment by Dlackjack** [comment]
Oh, sorry im restart server and all is work, thanks for help :D
