### ISSUE TITLE
Sirens

### ISSUE THREAD

**Issue by ChaserEraserTheSquadGaming** [TrevorBarns/luxart-vehicle-control#35]
Im having issues where the sirens arent synced the driver can hear the siren but the passenger cant hear it or sometimes if there is a player near me they here the default siren but if they turn on their siren they here the custom siren they have.

**Comment by TrevorBarns** [comment]
Thanks for the report! I have not heard anything like this but, looking through the code I might have an idea what could cause this.

- What version are you on?
- How quickly are you able to replicate this?
- Average player count when this occurs?
- Are you using OneSync?

**Comment by ChaserEraserTheSquadGaming** [comment]
3.2.4

within 5 mins

2-3 is all it has been tested with

Yes Non-Infinity OneSync

**Comment by TrevorBarns** [comment]
This is embarrassing, a mistake was made in prep for 3.2.4 release which resulted in incorrect event names. Please download the new revision 1 release here: https://github.com/TrevorBarns/luxart-vehicle-control/releases/tag/3.2.4

Sorry for any inconvenience.

**Comment by GGCHades** [comment]
I have updated to the latest version (3.2.4) and am using Onsync Infinity with a ESX Legacy base. My sirens do not sync at all to any other players.. This is including stock sirens.
