### ISSUE TITLE
Wrong Siren Tones Play

### ISSUE THREAD

**Issue by PapaFoxtrot404** [TrevorBarns/luxart-vehicle-control#39]
I am experiencing a bug in which the wrong tones play. Yes I have ensured the wm sirens were installed correctly. Yes the bottom of the sirens.lua list each vehicle GAME NAME with the corresponding numbers of its assigned sirens.

**Comment by PapaFoxtrot404** [comment]
`--[[
---------------------------------------------------
LUXART VEHICLE CONTROL V3 (FOR FIVEM)
---------------------------------------------------
Coded by Lt.Caine
ELS Clicks by Faction
Additions by TrevorBarns
---------------------------------------------------
FILE: SIRENS.lua
PURPOSE: Associate specific sirens with specific
vehicles. Siren assignments. 
---------------------------------------------------
SIREN TONE TABLE: 
	ID- Generic Name	(SIREN STRING)									[vehicles.awc name]
	1 - Airhorn 		(SIRENS_AIRHORN)								[AIRHORN_EQD]
	2 - Wail 			(VEHICLES_HORNS_SIREN_1)						[SIREN_PA20A_WAIL]
	3 - Yelp 			(VEHICLES_HORNS_SIREN_2)						[SIREN_2]
	4 - Priority 		(VEHICLES_HORNS_POLICE_WARNING)					[POLICE_WARNING]
	5 - CustomA* 		(RESIDENT_VEHICLES_SIREN_WAIL_01)				[SIREN_WAIL_01]
	6 - CustomB* 		(RESIDENT_VEHICLES_SIREN_WAIL_02)				[SIREN_WAIL_02]
	7 - CustomC* 		(RESIDENT_VEHICLES_SIREN_WAIL_03)				[SIREN_WAIL_03]
	8 - CustomE* 		(RESIDENT_VEHICLES_SIREN_QUICK_01)				[SIREN_QUICK_01]
	9 - CustomF* 		(RESIDENT_VEHICLES_SIREN_QUICK_02)				[SIREN_QUICK_02]
	10 - CustomG* 		(RESIDENT_VEHICLES_SIREN_QUICK_03)				[SIREN_QUICK_03]
	11 - Powercall 		(VEHICLES_HORNS_AMBULANCE_WARNING)				[AMBULANCE_WARNING]
	12 - FireHorn	 	(VEHICLES_HORNS_FIRETRUCK_WARNING)				[FIRE_TRUCK_HORN]
	13 - Firesiren 		(RESIDENT_VEHICLES_SIREN_FIRETRUCK_WAIL_01)		[SIREN_FIRETRUCK_WAIL_01]
	14 - Firesiren2 	(RESIDENT_VEHICLES_SIREN_FIRETRUCK_QUICK_01)	[SIREN_FIRETRUCK_QUICK_01]
]]
-- CHANGE SIREN NAMES, AUDIONAME, AUDIOREF

RequestScriptAudioBank("DLC_WMSIRENS\\SIRENPACK_ONE", false)

	SIRENS = {
	--[[1]]	  { Name = "Airhorn", 		String = "SIRENS_AIRHORN", 							Ref = 0 }, --1
	--[[2]]	  { Name = "Wail", 	        String = "VEHICLES_HORNS_SIREN_1", 					Ref = 0 }, --2
	--[[3]]	  { Name = "Yelp", 	        String = "VEHICLES_HORNS_SIREN_2", 					Ref = 0 }, --3
	--[[4]]	  { Name = "Priority", 		String = "VEHICLES_HORNS_POLICE_WARNING", 			Ref = 0 }, --4
	--[[5]]	  { Name = "Futura", 		String = "RESIDENT_VEHICLES_SIREN_WAIL_01", 		Ref = 0 }, --5
	--[[6]]	  { Name = "Hetro", 		String = "RESIDENT_VEHICLES_SIREN_WAIL_02", 		Ref = 0 }, --6
	--[[7]]	  { Name = "Sweep-1", 		String = "RESIDENT_VEHICLES_SIREN_WAIL_03", 		Ref = 0 }, --7
	--[[8]]	  { Name = "Sweep-2", 		String = "RESIDENT_VEHICLES_SIREN_QUICK_01", 		Ref = 0 }, --8
	--[[9]]	  { Name = "Hi-Low",		String = "RESIDENT_VEHICLES_SIREN_QUICK_02",		Ref = 0 }, --9
	--[[10]]  { Name = "Whine Down",	String = "RESIDENT_VEHICLES_SIREN_QUICK_03", 		Ref = 0 }, --10
	--[[11]]  { Name = "Powercall", 	String = "VEHICLES_HORNS_AMBULANCE_WARNING", 		Ref = 0 }, --11
	--[[12]]  { Name = "QSiren", 		String = "VEHICLES_HORNS_FIRETRUCK_WARNING", 		Ref = 0 }, --12
	--[[13]]  { Name = "Fire Yelp", 	String = "RESIDENT_VEHICLES_SIREN_FIRETRUCK_WAIL_01", 	Ref = 0 }, --13
	--[[14]]  { Name = "Fire Yelp", 	String = "RESIDENT_VEHICLES_SIREN_FIRETRUCK_QUICK_01", 	Ref = 0 }, --14
	--CUSTOM BELOW--
	--[[15]]  { Name = "Police Wail", 	String = "SIREN_ALPHA", 	Ref = "DLC_WMSIRENS_SOUNDSET" }, --15
	--[[16]]  { Name = "Police Prio", 	String = "SIREN_BRAVO", 	Ref = "DLC_WMSIRENS_SOUNDSET" }, --16
	--[[17]]  { Name = "Hecto", 	    String = "SIREN_CHARLIE", 	Ref = "DLC_WMSIRENS_SOUNDSET" }, --17
	--[[18]]  { Name = "Hi Lo", 	    String = "SIREN_DELTA", 	Ref = "DLC_WMSIRENS_SOUNDSET" }, --18
	--[[19]]  { Name = "Vintage", 	    String = "SIREN_ECHO", 	    Ref = "DLC_WMSIRENS_SOUNDSET" }, --19
	--[[20]]  { Name = "Powercall", 	String = "SIREN_FOXTROT", 	Ref = "DLC_WMSIRENS_SOUNDSET" }, --20
	--[[21]]  { Name = "Q Siren", 	    String = "SIREN_GOLF", 	    Ref = "DLC_WMSIRENS_SOUNDSET" }, --21
	--[[22]]  { Name = "Growler Horn",  String = "SIREN_HOTEL", 	Ref = "DLC_WMSIRENS_SOUNDSET" }, --22
}



--ASSIGN SIRENS TO VEHICLES
SIREN_ASSIGNMENTS = {
	--['<gameName>'] = {tones},
	['DEFAULT'] = { 1, 15, 16, 17 }, 
	['FIRETRUK'] = { 22, 21, 20, 18 }, 
	['AMBULAN'] = { 22, 18, 20, 17, 16 }, 
	['LGUARD'] = { 1, 2, 3, 4, 11 },
	--Custom--
	['lgc08ambo'] = { 22, 18, 17, 16 },
	['ChevySS'] = { 1, 15, 16, 17 },
	['Crown Victoria'] = { 1, 15, 16, 17 },
}
`

**Comment by TrevorBarns** [comment]
That issue is not fatal, it is well documented and only has to do with the HUD NUI. That is not causing your crashing. Try troubleshooting by disabling resources.

**Comment by PapaFoxtrot404** [comment]
ISSUE CLOSED: Adding custom sirens causes game crashes, or do not play at all is unresolved.

"Try troubleshooting by disabling resources."

**Comment by PapaFoxtrot404** [comment]
ISSUE CLOSED: Adding custom sirens causes game crashes, or do not play at all is unresolved.

"Try troubleshooting by disabling resources."
