### ISSUE TITLE
Support for WM-ServerSirens

### ISSUE THREAD

**Issue by TrevorBarns** [TrevorBarns/luxart-vehicle-control#4]
WM-ServerSirens is a server sided streaming resource. Build config option, instructions, schemes, vehicles.luas.

Submitted by VxperZ9421.

**Comment by Rior418** [comment]
Do you know when this will become a feature? You have taken lux to a new level already and this would just be amazing!

**Comment by TrevorBarns** [comment]
This will be implemented once https://github.com/TrevorBarns/luxart-vehicle-control/issues/12 is solved. At this state LVC is not stable for long term use. No point in adding additional features to a script that is not yet stable. It is not hard to implement and there is already information on WMs discord on how to convert LVCv3 to WM-ServerSiren. 

If this feature was going to be implemented I would do it "right" and make it as convenient as possible for server developers. But, like I said that takes time and a stable resource to begin with.

**Comment by TrevorBarns** [comment]
Implemented as of now. v.3.2.0 see SIRENS.LUA.
