### ISSUE TITLE
ragemenu.lua:92: Attempt to call a nil value (global 'IsPluginMenuOpen()' 

### ISSUE THREAD

**Issue by hollowlake** [TrevorBarns/luxart-vehicle-control#43]
LVC works until vehicle extras are changed. Then the following error appears:
ragemenu.lua:92: Attempt to call a nil value (global 'IsPluginMenuOpen()' )

Any ideas?

**Comment by TrevorBarns** [comment]
That function is defined in cl_plugins.lua in the PLUGINS folder. Does this file exist in your install? 

Are you on a Windows or Linux server?

**Comment by hollowlake** [comment]
I figured out that was missing right before you replied lol sorry man, thanks for response!
