### ISSUE TITLE
Set default HUD position server side

### ISSUE THREAD

**Issue by Mr-Chris-VRTY** [TrevorBarns/luxart-vehicle-control#44]
Hey,
is there a possibility to set the default HUD position server sided? So all players have the HUD at the same scale and position until they change it by there own? I dont find that option in the configs.

**Comment by TrevorBarns** [comment]
https://github.com/TrevorBarns/luxart-vehicle-control/wiki/FAQ#how-can-i-change-the-default-hud-location-for-my-server

**Comment by Mr-Chris-VRTY** [comment]
> https://github.com/TrevorBarns/luxart-vehicle-control/wiki/FAQ#how-can-i-change-the-default-hud-location-for-my-server

Thank you very much <3
