### ISSUE TITLE
[BUG] http https issue?

### ISSUE THREAD

**Issue by ViolentMinds** [TrevorBarns/luxart-vehicle-control#45]
`[     92016] [b2372_GTAProce]        CrBrowserMain/ Mixed Content: The page at 'https://cfx-nui-lvc//UI/html/index.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://lvc/hud:sendHudScale'. This request has been blocked; the content must be served over HTTPS. (@game/ui/jquery.js:8623)` caused a crash :(

**Comment by TrevorBarns** [comment]
What version are you using? I addressed this in v3.2.8.

**Comment by TrevorBarns** [comment]
Closing as this issue has been resolved as of v3.2.8. If you are running an older version you can download `\UI\html\lvc.js` from v3.2.8 or the master branch to resolve this error.
