### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by OnlyTheFamilyRp** [TrevorBarns/luxart-vehicle-control#46]
no siren or sound just lights

**Comment by TrevorBarns** [comment]
Yeaaahhh... That isn't quite enough information to even start debugging.

Consider joining the discord or provide more information like any console errors.

Also sirens are only enabled for VC_EMERGENCY class vehicles. Vehicle classes are set in the resources vehicle.meta.

**Comment by xrb936** [comment]
I have this issue as well. Just updated to 3.2.8. Only I can hear the siren when I am driving the car. Other people won't hear any sound.

**Comment by TrevorBarns** [comment]
> I have this issue as well. Just updated to 3.2.8. Only I can hear the siren when I am driving the car. Other people won't hear any sound.

This is a separate issue as the author of this issue reports no sirens locally as well.

**Comment by TrevorBarns** [comment]
@OnlyTheFamilyRp Any update on this?
