### ISSUE TITLE
No manual siren

### ISSUE THREAD

**Issue by PC1up** [TrevorBarns/luxart-vehicle-control#48]
So basically the manual siren (R-Button) doesn't work until you honk once. Tried it out, doesn't matter which Airhorn Behaviour is selected. Also tried it with enabling siren per 1/2/3-button, disabling siren and then trying manual. So seems like you really have to honk once to make manual siren work.

Edit: The SFX doesn't sound either

~Paul

**Comment by TrevorBarns** [comment]
Can you please attach a copy of your `cl_lvc.lua`?

Please check the console after behavior occurs for errors. Report back any findings. 

**Ensure you don't have a conflict with QBCore or another siren controller script.**

**Comment by PC1up** [comment]
Sorry for the late answer, cl_lvc.lua is right here: https://paste.md-5.net/zohawidudu.lua
Didn't find any errors in the console. I do have QBCore but that couldn't be the problem because I also have another server without QBCore which uses the same LVC Version and has the same problem.

**Comment by TrevorBarns** [comment]
After further review, I cannot replicate this error. I noticed the code has been modified, can you reproduce this in the latest version?

**Comment by PC1up** [comment]
Yeah, I modified the file to my own needs. Imma try the default code and change it step by step to find out what's causing this.
