### ISSUE TITLE
Sounds not playing

### ISSUE THREAD

**Issue by shawncreed** [TrevorBarns/luxart-vehicle-control#49]
Fresh install of LVC straight from the latest release on this repo. None of the sounds are working for me (as in the sounds generated by LVC, such as clicks, reminder beep, etc.; sirens and other sounds are fine). Have checked everything I can think of and can't figure out why it's not working. This is on a Linux server. Please let me know if you need any other information to troubleshoot and help resolve. Thank you. -Shawn

**Comment by TrevorBarns** [comment]
Hey Shawn, on the Linux server, did you install the Linux fxmanifest from the download?

Is there any errors in the console (server and F8)?

Are you using client side sirens or server side?

**Comment by shawncreed** [comment]
Hi @TrevorBarns and thanks for the quick reply.
- I did install the Linux-specific fxmanifest.lua.
- There are no errors in either server or client console
- I am using client side sirens. I can try restoring to the default sirens and see if that fixes the issue. Will report back.

**Comment by TrevorBarns** [comment]
Hmm let me look into this,.

**Comment by shawncreed** [comment]
I did restore my original RESIDENT.rpf file, cleared FiveM client and server cache, and tried again. Still no sounds at all from LVC. Will await a response from you when you have time to look into it. Thanks.

**Comment by TrevorBarns** [comment]
Can you perform factory reset? (Storage Management -> Factory Reset -> Confirm)

Also have you checked your volume settings? FiveM uses two different streams, one for game audio and another for NUI. NUI is what controls UI SFX.

**Comment by shawncreed** [comment]
Let me double check but I'm pretty sure I'm getting other NUI audio. (I do some FiveM dev also.)
Happy to try a factory reset though it was a fresh install when I noticed this issue so doubtful that will have an effect.

**Comment by TrevorBarns** [comment]
Hmm, okay do you know how to open NUI devtools? Should be a shortcut in FiveM menu (visible with console open) while in server. That is where NUI errors would log to html console.

**Comment by shawncreed** [comment]
I am not getting any errors in the NUI console, I just checked.
Did some more troubleshooting... I get clicks with the legacy version of LVC (when the resource was called "lux_vehcontrol") but not with the new version. So I am getting *some* NUI sounds, just not the NUI sounds from the latest version of LVC.

**Comment by shawncreed** [comment]
Disregard last... didn't realize legacy version didn't use NUI. So I don't think I'm getting any NUI sounds here. Any idea what could be causing that? I have all my audio routed to the right place as far as I can tell.

**Comment by TrevorBarns** [comment]
Did you test using this version? https://forum.cfx.re/t/release-luxart-vehicle-control-els-clicks/921644

This uses NUI soundfx.

I am thinking it has to do with fxmanifest/fivem not loading sound files. This could be a typo or error in the fxmanifest.

**Comment by shawncreed** [comment]
I can try with that version. However, I've realized I don't have sounds in another resource (the police radar) that uses NUI also. But I do in another server. Doesn't make any sense... why would a server side issue affect NUI sound?

**Comment by shawncreed** [comment]
Pretty recent (5364).

**Comment by shawncreed** [comment]
I tried updating to 5367 which is the recommended updated build from the txadmin Discord. Still nothing. Also I did try that version you linked a couple days ago that uses NUI and confirmed no sound. So I'm at a loss as to why I have no NUI sounds at all but only on my server. I didn't think it was possible for that to be a server-side (and server-WIDE meaning all resources) issue.

**Comment by shawncreed** [comment]
Got it working! Still confused as to why it worked on another server, but it looked like the application-specific sound routing in Windows had gotten "blanked out" for the Chromium subprocess used by NUI. I set it back to the correct device and it's working now. So weird. Anyways sorry for all the update spam here and thanks for your help. :)
