### ISSUE TITLE
Profile does not save Tone Options correctly

### ISSUE THREAD

**Issue by shawncreed** [TrevorBarns/luxart-vehicle-control#50]
When I change Tone Options for a particular siren (such as setting Priority to Button Only, which I always like to do), and then goto Storage Management > Save Settings and save my configuration, it doesn't restore when I'm back in the vehicle again later. Let me know what information I can provide to help troubleshoot further. Thank you. -Shawn

**Comment by TrevorBarns** [comment]
I have gotten reports on this, it used to work. I am a college student away from my PC currently but it is noted. Thanks for the report for corroborating other report.

**Comment by shawncreed** [comment]
At least I'm not alone. :) Thanks for the quick reply.

**Comment by shawncreed** [comment]
Not sure if related but it also doesn't seem to fully save my HUD settings (position is saved, but scale is not).

**Comment by TrevorBarns** [comment]
Both issues will be fixed in next release :) 

322273d195678a3323a226fc6e99c4a2d3c4738f
