### ISSUE TITLE
Radio controls not working

### ISSUE THREAD

**Issue by CallMeJwasTaken** [TrevorBarns/luxart-vehicle-control#51]
The Tilda key no longer seems to work for radio in emergency vehicles, I am on the latest LVC version.

**Comment by colman1911** [comment]
Same traffic.

**Comment by TrevorBarns** [comment]
Did yall download rev1? I pushed a fix.

**Comment by colman1911** [comment]
I downloaded as of about an hour before I commented, still no radio on my end.

**Comment by CallMeJwasTaken** [comment]
Ah, didnt know it was revised
It works now!
