### ISSUE TITLE
Native Error

### ISSUE THREAD

**Issue by ViolentMinds** [TrevorBarns/luxart-vehicle-control#52]
![image](https://user-images.githubusercontent.com/25211271/160300806-b62ecdf6-02f7-4480-b3a8-853b3b6e0335.png)

**Comment by TrevorBarns** [comment]
Please submit your settings.lua.

**Comment by ViolentMinds** [comment]
> Please submit your settings.lua.
[SETTINGS.lua.txt](https://github.com/TrevorBarns/luxart-vehicle-control/files/8359032/SETTINGS.lua.txt)

**Comment by TrevorBarns** [comment]
Unfortunately this is a complex issue with FiveM you might have to factory reset lvc and delete your lvc save data. Alternatively you may have to clear your kvps for the whole game.

This issue does not pertain to lvc. Try running factory reset under storage management.

**Comment by ViolentMinds** [comment]
Error seems to have disappeared!

Only one other unrelated issue remains for some people which is they bring up the controller and then then try to esc out of it and their mouse cursor gets stuck in the boundaries of where the control was. Not sure how they can fix that.

**Comment by TrevorBarns** [comment]
Please create a seperate issue for that.
