### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by JNordin96** [TrevorBarns/luxart-vehicle-control#53]
I can see the garbage message at the top but nothing else works. What a waste of my time.

![image](https://user-images.githubusercontent.com/102849116/161518686-edcdd0d3-d91c-4ca1-b604-3941febd4bfb.png)

**Comment by ConductorWon** [comment]
Maybe if you bothered to actually READ the message, it's telling you to download the latest RELEASE and not the MASTER branch. If you download the latest release it will work correctly once you configure it. Try putting in a little effort before bashing someone's script that almost 1000 servers currently use

**Comment by JNordin96** [comment]
Umm, I did download the lastest version. Literally the link you have on your page and followed each step. 

I got it to work by changing the resource folder name. Could have just said that in the instructions... Thanks

**Comment by JNordin96** [comment]
I'm a lawyer I read pretty well lol

**Comment by JNordin96** [comment]
![image](https://user-images.githubusercontent.com/102849116/161520917-0bc40f78-ebeb-4d2a-b199-932d1ec1bee1.png)

**Comment by JNordin96** [comment]
![image](https://user-images.githubusercontent.com/102849116/161520979-fd5f1b1b-13f0-4c4a-811e-58be99f6cca5.png)
Can you read that Conductor Won? Says latest version in green right there. That's what I did

**Comment by JNordin96** [comment]
Read the whole damn thing bud. Go back to bed

**Comment by ConductorWon** [comment]
Listen man, you xan cake screenshots all you want the code doesn't lie. The only way to get the image in the original screenshot is to download the master branch. And that "fix" you talked about, yeah theres code in the script that will prevent you from starting the resource unless it's named "lvc" and you know what? It tells you that too. So go ahead and use your "lawyer" skills and make up a phoney case to defend yourself but the facts don't lie. I'm sure you're used to hearing that anyway.

Enjoy the script.
