### ISSUE TITLE
Blackout function not working

### ISSUE THREAD

**Issue by shawncreed** [TrevorBarns/luxart-vehicle-control#55]
I haven't been able to get the blackout function to work on any vehicles. :( I've checked in the FiveM key binds to ensure I have the correct key mapped, and I've tried it with a few different key binds just in case. No luck. Any idea what might be going on?

**Comment by TrevorBarns** [comment]
https://github.com/TrevorBarns/luxart-vehicle-control/pull/54 was fixed in a recent pull request and will be fixed in the next update, feel free to download the changes if you want.

**Comment by shawncreed** [comment]
I got it working. Was a combination of the bug you mentioned (which I manually patched from the pull request) and not realizing there was a setting that needed toggling on in the config file. Oops. :) I do have a question though: I noticed it only retains the status of the brake lights and not the headlights. Is that by design? Because if I'm blacked out and I toggle it back on because, say, I need to chase someone, I have to manually turn my headlights back on.
