### ISSUE TITLE
LVC ERROR 2

### ISSUE THREAD

**Issue by TheT7F** [TrevorBarns/luxart-vehicle-control#56]
Hi, the sirens were working before. Now it doesn't work anymore. All files are as before.

Thanks in advance.
![whythis](https://user-images.githubusercontent.com/104315231/164985246-42fb572b-13df-4f9e-9e1a-6add15c588c1.PNG)

**Comment by TrevorBarns** [comment]
Check F8 for any additional errors.

Try saving the vehicle profile again under storage management.

**Comment by TheT7F** [comment]
I can't do 'o' in firetruk
![WhyError](https://user-images.githubusercontent.com/104315231/164986299-41a97f6c-94f2-4883-a3f9-07b0f414e4bb.PNG)

**Comment by TrevorBarns** [comment]
Can you attach your SIRENS.lua?

**Comment by TheT7F** [comment]
![w1](https://user-images.githubusercontent.com/104315231/164986923-f0cd4f41-25e0-40f8-9a29-36845b6c7814.PNG)
![w2](https://user-images.githubusercontent.com/104315231/164986928-9e6bc1f9-2b40-411b-8998-1f6e0a8aa790.PNG)
![w3](https://user-images.githubusercontent.com/104315231/164986932-6e81a44c-ca67-4698-915d-6409934b8118.PNG)

**Comment by TheT7F** [comment]
I will try to redo what I did on a clean script

**Comment by TrevorBarns** [comment]
Try running `/lvcfactoryreset` something with the saved tone data is broken

**Comment by TrevorBarns** [comment]
@TheT7F Where did you download the version of LVC that was causing the issue? I have found what was causing it though a different user, but am curious how you got the file so I can prevent others from having the same problem.

**Comment by TrevorBarns** [comment]
Issue is likely caused by improper newstate check. Another user reported issue, code attached:
```lua
function SetLxSirenStateForVeh(veh, newstate)
	if DoesEntityExist(veh) and not IsEntityDead(veh) then
		if newstate ~= state_lxsiren[veh] and newstate ~= nil then

			if snd_lxsiren[veh] ~= nil then
				StopSound(snd_lxsiren[veh])
				ReleaseSoundId(snd_lxsiren[veh])
				snd_lxsiren[veh] = nil
			end
			if newstate ~= 0 then    --Issue occurs when this line reads "if newstate ~= nil" otherwise index of SIRENS is 0 which doesn't exist in lua
				snd_lxsiren[veh] = GetSoundId()
				PlaySoundFromEntity(snd_lxsiren[veh], SIRENS[newstate].String, veh, SIRENS[newstate].Ref, 0, 0)
				TogMuteDfltSrnForVeh(veh, true)
			end
			state_lxsiren[veh] = newstate
		end
	end
end
```
