### ISSUE TITLE
For some reason the Hotkeys are in the settings but nothing works

### ISSUE THREAD

**Issue by StanGamerPro** [TrevorBarns/luxart-vehicle-control#58]
So, i have a custom FivePD server with my friend and we recently updated from Luxart by Lt.Cane to the newest release. However for some reason i cant get any of it to work, i have tried everything i can think of to get it to work, i have all of the keybinds listed in the Five M key binds section, but yet none of them work even for the default Police Cars. I would really like to get this working but i genuinely am out of ideas. If anyone could help me that would be dope! ill send ss and stuff if asked, but there are almost 0 Error codes and 0 indication as to why its not working

**Comment by TrevorBarns** [comment]
Can you please attach server & client log? I'd like to verify zero error codes claim. If nothing is working there would be some indication.

- Other things to keep in mind, LVC requires vehicles to be VC_EMERGENCY if you intend on using sirens.
- If on a linux server, install the fxmanifest for linux servers found on each release page.
- Install the required RageUI dependency provided in the download, it has custom modifications by me.
- Resource folder must be named 'lvc' and you cannot have 'lux_vehcontrol' (Lt.Caine's) running.

**Comment by TrevorBarns** [comment]
```
[ script:lvc] | __ ___ |
[ script:lvc] | / / /\ /\ / \ |
[ script:lvc] | / / \ \ / / / / |
[ script:lvc] | / / \ V / / /___ |
[ script:lvc] | _/uxart _/ ehicle _/ontrol |
[ script:lvc] | |
[ script:lvc] | COMMUNITY ID: |
[ script:lvc] | INSTALLED VERSION: 3.2.8 |
[ script:lvc] | LATEST VERSION: 3.2.8 |
[ script:lvc] | CONFIGURATION ERROR |
[ script:lvc] | COMMUNITY ID MISSING, THIS IS REQUIRED TO PREVENT |
[ script:lvc] | CONFLICTS FOR PLAYERS WHO PLAY ON MULTIPLE SERVERS |
[ script:lvc] | WITH LVC. PLEASE SET THIS IN SETTINGS.LUA. |
```

https://github.com/TrevorBarns/luxart-vehicle-control/wiki/Setup-&-Configuration#set-a-community-id

**Comment by StanGamerPro** [comment]
Ok give me a sec to modify the Config and restart the server and then ill let you know if it worked! thank you!

**Comment by StanGamerPro** [comment]
Ok ive come to the conclusion that i am dumb, and i love you lol, sorry for wasting your time but thanks for the help! It worked like a charm!
