### ISSUE TITLE
Only Blast Siren

### ISSUE THREAD

**Issue by BurlyDwalf1** [TrevorBarns/luxart-vehicle-control#59]
For some cars i can only blast the siren by holding R but i can toggle them with other emergency cars. this has the same vehicles.meta as the other car it works for apart from the name.

**Comment by BurlyDwalf1** [comment]
> 1. Verify you installed the latest release from the releases page, NOT the source code / master branch.
> 2. If you made any modifications to LVC revert them or reinstall `UTIL/cl_lvc.lua`.
> 3. Verify that the vehicles have vehicle class `VC_EMERGENCY`.
> 4. Start debugging by setting `debug_mode 'true'` in fxmanifest.lua, `refresh`, and `restart lvc`. This increases console printing.
> 5. Try disabling other resources that may be conflicting, some resources (especially frameworks) can conflict with siren control. Conflicts could include overriding siren states, blocking controls, etc. You may need to stop all other script based resources to figure out which one is conflicting.
> 
> I am guessing that another resource is blocking the other controls, as the manual siren key (R) is in the same section as all other controls.

Then why wold it works for most other cars?

**Comment by TrevorBarns** [comment]
Based on your chat and "emergency lights: activated" notifications it appears these are ELS vehicles. If this is the case, ELS vehicles are not supported by LVC. The likely culprit is `SetVehicleSiren` state is incorrect, LVC will not allow to toggle sirens unless `IsVehicleSirenOn` is true, which likely incorrectly set or being overridden by your other light/siren controller resource.

**Comment by BurlyDwalf1** [comment]
Is there a way i can use ELS With LVC?
