### ISSUE TITLE
Attempt to call a nil value (method 'BuildShortCutMenus') 

### ISSUE THREAD

**Issue by Snipeur060** [TrevorBarns/luxart-vehicle-control#66]
After 2/3 minutes some control of lvc don't work for example start light A or E but only the lock key work 
EDIT: (and no error is displayed)

**Comment by TrevorBarns** [comment]
Neither A nor E should toggle lights on LVC. Lvc uses Q for lights E for horn. Sounds like another resource is conflictint. Try disabling other resources.

**Comment by Snipeur060** [comment]
Hey i find something the problem is not with the E or A 
![image](https://user-images.githubusercontent.com/61784407/184639750-4720a1ce-f9b8-438d-a772-e634665b32c5.png)

**Comment by Snipeur060** [comment]
but this when you press the up arrow

**Comment by TrevorBarns** [comment]
Reinstall following the wiki, do not download source code.

**Comment by Snipeur060** [comment]
Same problem

**Comment by TrevorBarns** [comment]
Well you didn't delete the development files, you have to delete lvc and reinstall from the releases page you downloaded the source code that's still in development.

**Comment by Snipeur060** [comment]
yes and i do this now

**Comment by Snipeur060** [comment]
but change nothing

**Comment by TrevorBarns** [comment]
It's not a bug, you just aren't following the instructions. If you delete the lvc and download the release you will not have this issue. ![Screenshot_20220815-094155.png](https://user-images.githubusercontent.com/62955754/184656859-995a199e-01fe-41af-8a87-5ed88748b338.png)

**Comment by Snipeur060** [comment]
Do you understand that I do what you said before download the release but it's the same thing

**Comment by Snipeur060** [comment]
I have the same problem

**Comment by Snipeur060** [comment]
I delete and reinstall lvc

**Comment by TrevorBarns** [comment]
I don't know how to help you that error is associated with code that cannot be found in 'Luxart.Vehicle.Control.v3.2.8-rev1.zip', it was written yet. 

If you've deleted all of your lvc folder and reinstalled lvc following the wiki, it isn't possible for that error to occur.

Either:
- you didn't clear lvc folder and it's content and just installed it on top of existing source code.
- downloaded the source code again and not the release zip.
- did not refresh and restart lvc.
- or are getting a different error.

**Comment by Snipeur060** [comment]
I do all of this thing

**Comment by Snipeur060** [comment]
<img width="923" alt="image" src="https://user-images.githubusercontent.com/61784407/184668967-e9d93c5a-ce1b-4bf0-ba1d-12b24343525f.png">

**Comment by Snipeur060** [comment]
Note the same when you pressed up arrow

**Comment by TrevorBarns** [comment]
Okay, that is a completely different error. That error occurs when RageUI is not installed correctly.
> 2. Copy `RageUI` folder from 'dependencies' folder in resources folder.

**Comment by Snipeur060** [comment]
i have a question i already have rageui and i need to put this rageui ?

**Comment by Snipeur060** [comment]
I will try

**Comment by Snipeur060** [comment]
So now i have another problem a little part of vehicules don't work you press E and you have the light but lvc don't control this vehicule 
https://github.com/TrevorBarns/luxart-vehicle-control/issues/61
Same problem 
But i change the meta and nothing

**Comment by Snipeur060** [comment]
And thanks up arrow work now

**Comment by Snipeur060** [comment]
if you have any fix i will take it (all of the car have the flag emergency and led)

**Comment by TrevorBarns** [comment]
You referenced #61 which was a user error with vehicle installation. You likely have the same problem.

LVC only requires:
- emergency vehicle class
- profile (gameName or fallback 'DEFAULT')

If it is not working it is a problem with your vehicle installation / configuration. I am not sure what insight I can provide.

**Comment by Snipeur060** [comment]
So gamename and it's good ?

**Comment by TrevorBarns** [comment]
No.

You either need a profile for that vehicle using the vehicles game name OR a DEFAULT profile table. Which you likely already have. 

If it's still not working its a problem with vehicle.

**Comment by Snipeur060** [comment]
<modelName>megane3pn</modelName>
      <txdName>megane3pn</txdName>
      <handlingId>POLICE</handlingId>
      <gameName>POLICE</gameName>
      <vehicleMakeName>RENAULT</vehicleMakeName>
      <expressionDictName>null</expressionDictName>
      <expressionName>null</expressionName>
      <animConvRoofDictName>null</animConvRoofDictName>
      <animConvRoofName>null</animConvRoofName>
      <animConvRoofWindowsAffected />
      <ptfxAssetName>null</ptfxAssetName>
      <audioNameHash>POLICE</audioNameHash>

**Comment by Snipeur060** [comment]
this will be correct ?

**Comment by TrevorBarns** [comment]
In that case in your SIRENS.lua you would use:

`['POLICE'] = {...}`

**Comment by Snipeur060** [comment]
I will try

**Comment by Snipeur060** [comment]
It's good i find why 
      `<type>VEHICLE_TYPE_EMERGENCY</type>`
`<vehicleClass>VC_EMERGENCY</vehicleClass>`
Need to be on this value
