### ISSUE TITLE
Creating a new UI

### ISSUE THREAD

**Issue by ToddCarson44** [TrevorBarns/luxart-vehicle-control#67]
I play in a server that is Stricly 70s based and Im trying to create a new siren control box theme. I changed the background , (The texture is a little larger) but I cant seem to find the correct file to allow the full resolution of the image instead of the default res. Same issue with the buttons, they seem to keep the original size. Here is an example
![image](https://user-images.githubusercontent.com/111051725/184106623-ad5ab790-148f-4f57-b81d-012c5c6a7104.png)

**Comment by TrevorBarns** [comment]
`style.css` contains NUI CSS parameters that control the layout. Change the width and height of those. It can take a while to figure it out. I'd recommend using the NUI dev console so you can change values on the fly without restarting.
