### ISSUE TITLE
attempt to call nil global IsMenuOpen error

### ISSUE THREAD

**Issue by ajrob202** [TrevorBarns/luxart-vehicle-control#68]
Hello! Everytime my players open vMenu or  sometimes randomly, they get this error.

![image](https://user-images.githubusercontent.com/112226673/187011420-4e0a0fb4-bca8-4c29-95a2-da9b9207187f.png)

After this, LVC stops working. Lights, siren, horn, nothing works. Any fix for this? Thanks!

**Comment by TrevorBarns** [comment]
Verify that cl_plugins.lua is located in the PLUGINS folder. If not install lvc following the wiki and it should fix it.

If you're on Linux make sure you use the fxmanifest for Linux from the releases page.
