### ISSUE TITLE
Siren cycle crash when all siren are "Button only"

### ISSUE THREAD

**Issue by Salzian** [TrevorBarns/luxart-vehicle-control#7]
When trying to cycle the sirens with `R` while all tones are set to _"Button only"_, the client starts to hang indefinitely.

Version: 3.1.3-beta

## Reproduction

1. Spawn any emergency vehicle and enter it
2. Open Menu using `O`
3. Go to _"Main Siren Settings"_ menu
4. Set all tones to _"Button only"_
5. Close menu
6. Activate lights & siren `(Alt + Q)`
7. Press `R` to cycle

## Expected behaviour

Nothing, there are no sirens to cycle through.

## Actual behaviour

The FiveM client hangs and can only be closed using the task manager.

## Suspicion

I believe there may be an infinite loop going on trying to cycle through an empty list of sirens, since none are enabled for the _"cycle"_ mode.

https://github.com/TrevorBarns/luxart-vehicle-control/blob/6c2ad06fabfa318a07aa25386dd1179e1cd0d550/client.lua#L611-L647

Unfortunately my LUA knowledge is not sufficient enough to debug a script of this size myself.

**Comment by TrevorBarns** [comment]
That is interesting that you were able to disable all sirens. I added a check but there must be a bug related to that.
https://github.com/TrevorBarns/luxart-vehicle-control/blob/6c2ad06fabfa318a07aa25386dd1179e1cd0d550/menu.lua#L322-L330

https://github.com/TrevorBarns/luxart-vehicle-control/blob/6c2ad06fabfa318a07aa25386dd1179e1cd0d550/menu.lua#L122-L134

Thank you so much for the detailed bug report, this will come in very useful.

**Comment by TrevorBarns** [comment]
Fixed as of version 3.1.5-beta. 
https://github.com/TrevorBarns/luxart-vehicle-control/releases/tag/3.1.5
