### ISSUE TITLE
Premade Siren Mega Pack Partially Working

### ISSUE THREAD

**Issue by MoubyCT** [TrevorBarns/luxart-vehicle-control#72]
All the sirens from FIB and down do not work ingame. The rest works fine.
eg; siren table numbers 39 to 50 do not stream the sound.
SAS is installed.

--[[39]] { Name = 'CGOLD-HORN', String = 'OISS_SSA_VEHAUD_FIB_NEW_HORN', Ref = 'OISS_SSA_VEHAUD_FIB_NEW_SOUNDSET'},
--[[40]] { Name = 'CGOLD-WAIL', String = 'OISS_SSA_VEHAUD_FIB_NEW_SIREN_ADAM', Ref = 'OISS_SSA_VEHAUD_FIB_NEW_SOUNDSET'},
--[[41]] { Name = 'CGOLD-YELP', String = 'OISS_SSA_VEHAUD_FIB_NEW_SIREN_BOY', Ref = 'OISS_SSA_VEHAUD_FIB_NEW_SOUNDSET'},
--[[42]] { Name = 'CGOLD-PRIORITY', String = 'OISS_SSA_VEHAUD_FIB_NEW_SIREN_CHARLES', Ref = 'OISS_SSA_VEHAUD_FIB_NEW_SOUNDSET'},
--[[43]] { Name = 'CGOLD-SWEEP', String = 'OISS_SSA_VEHAUD_FIB_NEW_SIREN_DAVID', Ref = 'OISS_SSA_VEHAUD_FIB_NEW_SOUNDSET'},
--[[44]] { Name = 'CGOLD-SWEEP3', String = 'OISS_SSA_VEHAUD_FIB_NEW_SIREN_EDWARD', Ref = 'OISS_SSA_VEHAUD_FIB_NEW_SOUNDSET'},
--[[45]] { Name = 'FIRE HORN', String = 'OISS_SSA_VEHAUD_LSFD_NEW_HORN', Ref = 'OISS_SSA_VEHAUD_LSFD_NEW_SOUNDSET'},
--[[46]] { Name = 'POWERCALL', String = 'OISS_SSA_VEHAUD_LSFD_NEW_SIREN_ADAM', Ref = 'OISS_SSA_VEHAUD_LSFD_NEW_SOUNDSET'},
--[[47]] { Name = 'Q-COAST', String = 'OISS_SSA_VEHAUD_LSFD_NEW_SIREN_BOY', Ref = 'OISS_SSA_VEHAUD_LSFD_NEW_SOUNDSET'},
--[[48]] { Name = 'Q-HIGH', String = 'OISS_SSA_VEHAUD_LSFD_NEW_SIREN_CHARLES', Ref = 'OISS_SSA_VEHAUD_LSFD_NEW_SOUNDSET'},
--[[49]] { Name = 'Q-MID', String = 'OISS_SSA_VEHAUD_BCFD_NEW_SIREN_DAVID', Ref = 'OISS_SSA_VEHAUD_BCFD_NEW_SOUNDSET'},
--[[50]] { Name = 'Q-MID2', String = 'OISS_SSA_VEHAUD_BCFD_NEW_SIREN_EDWARD', Ref = 'OISS_SSA_VEHAUD_BCFD_NEW_SOUNDSET'},

**Comment by TrevorBarns** [comment]
Please attach your SIRENS.lua entirely. Also please test to see if they play using [SSAT](https://github.com/TrevorBarns/Server-Side-Audio-Tester)

**Comment by MoubyCT** [comment]
[SIRENS.zip](https://github.com/TrevorBarns/luxart-vehicle-control/files/9758530/SIRENS.zip)

They did not work using SSAT.

**Comment by TrevorBarns** [comment]
That's an issue on SAS side then. Can you send a screenshot of your Server Sided Audio and Sirens resource folder with the AWCs?

**Comment by MoubyCT** [comment]
https://prnt.sc/4Jwts4z1JE7Q [Main folder]
https://prnt.sc/RzaCloBnnkS- [Inside the _work folder.]
https://prnt.sc/CAieGUg-GIZm [Inside the data folder.]
https://prnt.sc/QHxSGJkEooeg [Inside of the dlc folder.]
https://prnt.sc/58llf8ljdQFN [Inside of the oac folder.]

**Comment by TrevorBarns** [comment]
https://docs.luxartengineering.com/v3/resource-installation/server-sided-siren-integration#1.-request-audio-bank
![](https://i.imgur.com/FmOPbnP.png)

You have requested 34 audio banks. Delete those and only put in the [ones included in the mega pack](https://github.com/TrevorBarns/luxart-vehicle-control-extras/tree/master/Siren%20Packs/Server%20Sided%20Mega%20Pack%20A%20(5%2B1)#whelen-295hfs5a-fs2000sm-touchmaster-delta-code-3-mastercom-b-whelen-cencom-gold-wfire-rescue) 
```lua
RequestScriptAudioBank('DLC_SERVERSIDEAUDIO\\OISS_SSA_VEHAUD_LSPD_NEW', false)
RequestScriptAudioBank('DLC_SERVERSIDEAUDIO\\OISS_SSA_VEHAUD_LSSD_NEW', false)
RequestScriptAudioBank('DLC_SERVERSIDEAUDIO\\OISS_SSA_VEHAUD_BCSO_NEW', false)
RequestScriptAudioBank('DLC_SERVERSIDEAUDIO\\OISS_SSA_VEHAUD_SAHP_NEW', false)
RequestScriptAudioBank('DLC_SERVERSIDEAUDIO\\OISS_SSA_VEHAUD_FIB_NEW', false)
RequestScriptAudioBank('DLC_SERVERSIDEAUDIO\\OISS_SSA_VEHAUD_LSFD_NEW', false)
RequestScriptAudioBank('DLC_SERVERSIDEAUDIO\\OISS_SSA_VEHAUD_BCFD_NEW', false)
```
