### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MoubyCT** [TrevorBarns/luxart-vehicle-control#73]
Addon sirens dont work on certain vehicles, even though theyre correctly named in siren lua.

Error as following;

[    722281] [b2699_GTAProce]             MainThrd/ ^3LVC(3.2.9) Warning %{code}: attempted to set tone PMANU but, was unable to locate position: 2 in approved_tones. (UTIL:SetToneByPos(PMANU, %{pos}). Try factory resetting as this may occur after siren tone assignments change.

[    722297] [b2699_GTAProce]             MainThrd/ ^3LVC(3.2.9) Warning %{code}: attempted to set tone SMANU but, was unable to locate position: 3 in approved_tones. (UTIL:SetToneByPos(SMANU, %{pos}). Try factory resetting as this may occur after siren tone assignments change.

[    722297] [b2699_GTAProce]             MainThrd/ ^3LVC(3.2.9) Warning %{code}: attempted to set tone AUX but, was unable to locate position: 2 in approved_tones. (UTIL:SetToneByPos(AUX, %{pos}). Try factory resetting as this may occur after siren tone assignments change.

**Comment by TrevorBarns** [comment]
These are warnings not errors, just save that profile again in Storage Management menu. It's just saying your previous save has tones that are no longer approved for the vehicle.

**Comment by MoubyCT** [comment]
alright, thanks!
