### ISSUE TITLE
I can't hear the siren

### ISSUE THREAD

**Issue by FraterTater15** [TrevorBarns/luxart-vehicle-control#75]
I installed sirens for every department and other people in the server can hear it but I can't. The server I am in has it set up as a client side thing. I can't hear the sirens.

**Comment by TrevorBarns** [comment]
Are you using server sided sirens or client side (RESIDENT.rpf)?

**Comment by FraterTater15** [comment]
client side I think how would I tell

**Comment by TrevorBarns** [comment]
If you can attach your SIRENS.lua, it likely is client side, in that case it has to do with your RESIDENT.rpf and vehicles.awc where client side sirens are located. You could test it on another server or without LVCv3 in. I believe it has to do with your GTA V siren install.
