### ISSUE TITLE
certan siren tones not working on certain vehicles

### ISSUE THREAD

**Issue by bware600** [TrevorBarns/luxart-vehicle-control#76]
So some cars the server side sirens are working on fine but some aren't working at all it just has default. Any ideas why this is?

**Comment by bware600** [comment]
--ASSIGN SIRENS TO VEHICLES
SIREN_ASSIGNMENTS = {
	--['<gameName>'] = {tones},
	['DEFAULT'] = { 1, 2, 3, 4 },
	['295-gameName'] = { 15, 16, 17, 18, 19, 20 },
	['FS-gameName'] = { 21, 22, 23, 24, 25, 26 },
	['TMD-gameName'] = { 27, 28, 29, 30, 31, 32 },
	['MCB-gameName'] = { 33, 34, 35, 36, 37, 38 },
	['CenCom-gameName'] = { 39, 40 ,41, 42, 43, 44 },
	['fire-GameName'] = { 46, 49, 50, 48, 46 },
	['code319silv'] = { 21, 22, 23, 24, 25, 26 },
	['code320exp'] = { 21, 22, 23, 24, 25, 26 },
	['code3bmw'] = { 21, 22, 23, 24, 25, 26 },
	['code3boat'] = { 21, 22, 23, 24, 25, 26 },
	['code3camero'] = { 21, 22, 23, 24, 25, 26 },
	['code3cap'] = { 21, 22, 23, 24, 25, 26 },
	['code3cvpi'] = { 21, 22, 23, 24, 25, 26 },
	['code3durango'] = { 21, 22, 23, 24, 25, 26 },
	['code3f150'] = { 21, 22, 23, 24, 25, 26 },
	['code3f250'] = { 21, 22, 23, 24, 25, 26 },
	['code3fpis'] = { 21, 22, 23, 24, 25, 26 },
	['code310charg'] = { 21, 22, 23, 24, 25, 26 },
	['code314charg'] = { 21, 22, 23, 24, 25, 26 },
	['code314tahoe'] = { 21, 22, 23, 24, 25, 26 },
	['code316fpiu'] = { 21, 22, 23, 24, 25, 26 },
	['code316impala'] = { 21, 22, 23, 24, 25, 26 },
	['code318charg'] = { 21, 22, 23, 24, 25, 26 },
	['code318chargk9'] = { 21, 22, 23, 24, 25, 26 },
	['code319silv'] = { 21, 22, 23, 24, 25, 26 },
	['code3gator'] = { 21, 22, 23, 24, 25, 26 },
	['code3harley'] = { 21, 22, 23, 24, 25, 26 },
	['code3mustang'] = { 21, 22, 23, 24, 25, 26 },
	['code3ram'] = { 21, 22, 23, 24, 25, 26 },
	['code3silverado'] = { 21, 22, 23, 24, 25, 26 },
	['code318tahoe'] = { 21, 22, 23, 24, 25, 26 },
	['smallboat'] = { 21, 22, 23, 24, 25, 26 },
	['largeboat'] = { 21, 22, 23, 24, 25, 26 },
	['HILLBOATY'] = { 21, 22, 23, 24, 25, 26 },
	['squad2'] = { 39, 40 ,41, 42, 43, 44 },
	['rampov'] = { 39, 40 ,41, 42, 43, 44 },
	['f250pov'] = { 39, 40 ,41, 42, 43, 44 },
	['dagor'] = { 39, 40 ,41, 42, 43, 44 },
	['slrr'] = { 39, 40 ,41, 42, 43, 44 },
	['fordambo'] = { 39, 40 ,41, 42, 43, 44 },
	['20ramambo'] = { 39, 40 ,41, 42, 43, 44 },
	['ladder66'] = { 45, 49, 50, 48, 46 },
	['ftank'] = { 45, 49, 50, 48, 46 },
	['frescue'] = { 45, 49, 50, 48, 46 },
	['enforcer'] = { 45, 49, 50, 48, 46 },
	['enforcerta'] = { 45, 49, 50, 48, 46 },
	['enforcerf'] = { 45, 49, 50, 48, 46 },
	['arrowrescue'] = { 45, 49, 50, 48, 46 },
	['f550cskeeter6'] = { 39, 40 ,41, 42, 43, 44 },
	['lib15f150'] = { 15, 16, 17, 18, 19, 20 },
	['lib19tahoe'] = { 15, 16, 17, 18, 19, 20 },
	['lib19silverado'] = { 15, 16, 17, 18, 19, 20 },
	['lib19camaro'] = { 15, 16, 17, 18, 19, 20 },
	['lib18taurus'] = { 15, 16, 17, 18, 19, 20 },
	['lib18charger'] = { 15, 16, 17, 18, 19, 20 },
	['lib16explorer'] = { 15, 16, 17, 18, 19, 20 },
	['lib14tahoe'] = { 15, 16, 17, 18, 19, 20 },
	['lib14ram'] = { 15, 16, 17, 18, 19, 20 },
	['lib14charger'] = { 15, 16, 17, 18, 19, 20 },
	['lib12caprice'] = { 15, 16, 17, 18, 19, 20 },
	['lib11vic'] = { 15, 16, 17, 18, 19, 20 },
	['wildlifesilv'] = { 15, 16, 17, 18, 19, 20 },
	['wildliferam'] = { 15, 16, 17, 18, 19, 20 },
	['wildlifeboat2'] = { 15, 16, 17, 18, 19, 20 },
	['wildlifeboat1'] = { 15, 16, 17, 18, 19, 20 },
	['wildlife20tahoe'] = { 15, 16, 17, 18, 19, 20 },
	['wildlife14tahoe'] = { 15, 16, 17, 18, 19, 20 },
	['pd20exped'] = { 15, 16, 17, 18, 19, 20 },
	['legacy1'] = { 27, 28, 29, 30, 31, 32 },
	['legacy2'] = { 27, 28, 29, 30, 31, 32 },
	['legacy3'] = { 27, 28, 29, 30, 31, 32 },
	['legacy4'] = { 27, 28, 29, 30, 31, 32 },
	['legacu5'] = { 27, 28, 29, 30, 31, 32 },
	['legacy6'] = { 27, 28, 29, 30, 31, 32 },
	['legacy7'] = { 27, 28, 29, 30, 31, 32 },
	['legacy8'] = { 27, 28, 29, 30, 31, 32 },
	['legacy9'] = { 27, 28, 29, 30, 31, 32 },
	['legacy10'] = { 27, 28, 29, 30, 31, 32 },
	['legacy11'] = { 27, 28, 29, 30, 31, 32 },
	['legacy12'] = { 27, 28, 29, 30, 31, 32 },
	['legacy13'] = { 27, 28, 29, 30, 31, 32 },
	['legacy14'] = { 27, 28, 29, 30, 31, 32 },
	['legacy15'] = { 27, 28, 29, 30, 31, 32 },
	['speedc8bb'] = { 27, 28, 29, 30, 31, 32 },
	['speeddemonbb'] = { 27, 28, 29, 30, 31, 32 },
	['at420bb'] = { 27, 28, 29, 30, 31, 32 },
}

This is my siren assignments btw and i dont see whats causing it.

**Comment by TrevorBarns** [comment]
If some sirens work on the "broken" vehicles and others don't, test those tones using [SSAT](https://github.com/TrevorBarns/Server-Side-Audio-Tester). They may be too large to be streamed.

**Comment by TrevorBarns** [comment]
If it's using the default the game name is incorrect.

https://docs.luxartengineering.com/v3/faq#why-is-this-vehicle-still-using-the-default-profile-even-after-i-created-a-table-in-sirens_assignmen

**Comment by bware600** [comment]
second option fixed it. thanks.
