### ISSUE TITLE
i have installed everything correctly and it just flat out dosent work [BUG]

### ISSUE THREAD

**Issue by oman9000999** [TrevorBarns/luxart-vehicle-control#78]
**Installed Version** (Base and Plugin if applicable)
base: v3.9.9 - extra integration: v1.9.9

**Describe the bug**
when ever i run the server and get in an emergency vehicle i dont see the pop up, neither does the menu open or show any key binds in fivem. it also dosent show in the recources in txadmin.
![image](https://user-images.githubusercontent.com/97201398/215392793-59dd43cd-3e3c-41e2-92c4-135388d380e9.png)

**Comment by TrevorBarns** [comment]
This is not a bug, if the resource isn't showing in txadmin then the installation is not correct. Verify you have followed the steps here: https://docs.luxartengineering.com/v3/resource-installation

Please provide a screenshot of your lvc directory and run `refresh` on your server console to check for any errors detecting the resource. If you are on a linux server make sure to use the fxmanifest for linux server found on the release page as the default is not compatible.
