### ISSUE TITLE
LVC doesnt work after closing any menu

### ISSUE THREAD

**Issue by mikaw-22** [TrevorBarns/luxart-vehicle-control#80]
When im in a Menu like NativeUI or others, while sitting in a emergency car and navigate in this menu and closing it, lvc doesnt work anymore. I have to restart the resource every time to get it worked again. this is the error after closing a menu and trying to press Q to start the siren.
![image](https://user-images.githubusercontent.com/112482688/218260836-edd690df-2031-45fd-b1fc-d31306e43833.png)

**Comment by TrevorBarns** [comment]
Reinstall RageUI included in LVCs release.

https://docs.luxartengineering.com/v3/resource-installation

> "LVC utilizes a modified release of RageUI, please install it even if you already have another version installed."
