### ISSUE TITLE
[LVC stopped working]

### ISSUE THREAD

**Issue by AronStaIka** [TrevorBarns/luxart-vehicle-control#81]
Everytime someone changes an Extra, Changes Color or even just Upgrade an Vehicle, LVC stopped working.

I need to restart the Script everytime to get it back working.
i got Error messages lke this 2 times when i restart the Script:

SCRIPT ERROR: @lvc/PLUGINS/cl_plugins.lua:31: attempt to call a nil value (global 'IsMenuOpen')

Any idea on how to solve this problem?

![problem 1](https://github.com/TrevorBarns/luxart-vehicle-control/assets/134186211/1bc324f7-9395-40e4-8204-1363a6c04f0a)
![problem 2](https://github.com/TrevorBarns/luxart-vehicle-control/assets/134186211/40e224f0-7d41-44ed-9dce-fec67a64349b)

**Comment by TrevorBarns** [comment]
The custom version of RageUI provided in the release is either not installed or not able to start. See docs for installation instructions.

**Comment by AronStaIka** [comment]
> The custom version of RageUI provided in the release is either not installed or not able to start. See docs for installation instructions.

On it.

And thanks for the quick Response.

**Comment by AronStaIka** [comment]
Got the same problem.

![problem 3](https://github.com/TrevorBarns/luxart-vehicle-control/assets/134186211/8fa3fc6c-7274-47c4-ad4b-0c5d4b666290)

**Comment by AronStaIka** [comment]
Problem is gone.

Thank you.
