### ISSUE TITLE
[BUG] Vehicle names error

### ISSUE THREAD

**Issue by NitchgamingStudios** [TrevorBarns/luxart-vehicle-control#84]
**Installed Version** (Base and Plugin if applicable)
base: 3.2.9

**Describe the bug**
When you add a vehicle to the SIRENS.lua file to use a custom siren setting, if the vehicle name has an '_' in it, (i.e rfs_cat6), the sirens do not change. However when the '_' is removed it fixes the issue.

**To Reproduce**
1. Add the spawncode with the '_' to the SIRENS.lua to use custom siren settings.
2. Save and restart
3. Spawn the vehicle and test the sirens

**Expected behavior**
Sirens for the specified vehicle should change to follow what was done on the SIRENS.lua file

**Screenshots**
![image](https://github.com/TrevorBarns/luxart-vehicle-control/assets/72492013/b012f377-a196-4946-b1e2-57e96801910d)

**Comment by TrevorBarns** [comment]
Thanks for the report. Underscores in gameNames are automatically converted to spaces by GTA V. It makes sense as they don't support underscores and want to display a string to the game UI.

So if you set your key to `['rfs cat6']` it should work. I'll consider adding a replacement function to do this behind the scenes.

**Comment by NitchgamingStudios** [comment]
Thanks for that!. It would be great if you could try to do that!
