### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JaysonLLL** [TrevorBarns/luxart-vehicle-control#85]
**I configured it normally, but it didn't work**
![image](https://github.com/TrevorBarns/luxart-vehicle-control/assets/66419064/9999a26d-a1e0-4a94-93c5-d1516299eeaa)

![image](https://github.com/TrevorBarns/luxart-vehicle-control/assets/66419064/ae112dd4-b862-453c-9bac-2a759ee5ad3c)

**Comment by JaysonLLL** [comment]
SCRIPT ERROR: @lvc/UTIL/semver.lua:189: attempt to compare number with nil

**Comment by LYJayson** [comment]
![image](https://github.com/TrevorBarns/luxart-vehicle-control/assets/66419064/1db93778-794f-418a-a935-ec2912221361)
