### ISSUE TITLE
[BUG] Unable to remove the controls for hazards and turn signals

### ISSUE THREAD

**Issue by WildFyr16** [TrevorBarns/luxart-vehicle-control#89]
## Installed Version
(Base and Plugin if applicable)
base: v3.2.9 - extra integration: v1.2.1

## Describe the bug
There is no native way to remove the controls for the turn signals and hazards. I have a vehicle HUD script that also adds blinkers and turns signals with more functionality and sounds, but when I try to comment out the controls in LVC it bugs out and things like the V key start to activate the hazards and another button we have yet to locate fully to turn on the left hand turn signal. I think it would be nice to have a "Use LVC Turn Signals and Hazards" option in the settings.lua to just outright disable the turn signals and hazards if the server wants.

## To Reproduce
First disable the Turn Signal and Hazards button controls in the settings
Restart your server and press V (at least for our server) in a car and see your hazards come on.

## Expected behavior
The ability to fully disable the turn signals and hazards would be super helpful to server developers

## Screenshots
**NULL**

## Additional context
**NULL**

**Comment by TrevorBarns** [comment]
How did you "disable the turn signal and hazard button controls in the settings"? 

Please post your modifications or changes to the resource.

**Comment by WildFyr16** [comment]
So I found my issue, a very basic one at that... forgot a few formatting things in the code.
I created a PR for this so other users may use or can be merged right in [here](https://github.com/TrevorBarns/luxart-vehicle-control/pull/90)
