### ISSUE TITLE
SCRIPT ERROR: pointer result matches an argument

### ISSUE THREAD

**Issue by KEKHUBCypherWalls** [TrevorBarns/luxart-vehicle-control#96]
Since i updated my es_extended from Legacy 1.10.7 to 1.10.9 now i get many errors...

Client Console:
![grafik](https://github.com/user-attachments/assets/6fbb8c20-296b-437a-a4b6-138ce1a45608)
Server Console:
![grafik](https://github.com/user-attachments/assets/17e18c0e-4f7e-4f26-80da-9ca906abefc1)
lvc/UTIL/cl_storage.lua:338
![grafik](https://github.com/user-attachments/assets/de0b73a3-9bd3-40d1-9038-8d8fbee35c7d)
lvc/UTIL/cl_storage.lua:292
![grafik](https://github.com/user-attachments/assets/7e0e90b0-e8c5-4442-a3b9-a26013735514)
lvc/UTIL/cl_lvc.lua:218
![grafik](https://github.com/user-attachments/assets/fa89f191-6a08-42a4-98ea-b519c0388aef)
lvc/UTIL/cl_utils.lua/292
![grafik](https://github.com/user-attachments/assets/3824c0b6-10c6-438d-9af4-441b40ca22f2)
lvc/UTIL/cl_lvc.lua:705
![grafik](https://github.com/user-attachments/assets/92a21bee-652d-482c-ac85-b9dc61f2de16)

Can anybody help?

**Comment by TrevorBarns** [comment]
@KEKPandinjaPlayroom what was the issue?

**Comment by KEKHUBCypherWalls** [comment]
There was no error from the script, I restarted the server once and then it worked again as usual.
